/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef pmmrpc_CONSTANTS_H
#define pmmrpc_CONSTANTS_H

#include "pmmrpc_types.h"

namespace pmmrpc {

class pmmrpcConstants {
 public:
  pmmrpcConstants();

};

extern const pmmrpcConstants g_pmmrpc_constants;

} // namespace

#endif
