/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "pmmrpc_constants.h"

namespace pmmrpc {

const pmmrpcConstants g_pmmrpc_constants;

pmmrpcConstants::pmmrpcConstants() {
}

} // namespace

